import type { NextPage } from 'next';
import Head from 'next/head';

import SweepCartPageTemplate from '../../../src/templates/sweeptemplatecart';

// http://localhost:3000/sweep/lineup
const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SweepCartPageTemplate /> */}
    </>
  );
};

export default Main;
