import type { NextPage, GetServerSideProps } from 'next';

import Head from 'next/head';

import SweepDeliveryInfoInputTemplate from '../../../src/templates/sweepdeliveryinfoinputtemplate';
import { CART_DELIVERY_CONFIRM } from '../../../src/common/sweep/setting';

export interface DeliveryInfoProps {
  isModifyInfo: boolean;
}

const Main: NextPage<DeliveryInfoProps> = (props) => {
  // 確認画面からの遷移かどうか？
  const modify = props.isModifyInfo;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SweepDeliveryInfoInputTemplate isModifyInfo={modify} />
    </>
  );
};

// サーバーサイドの処理を実施してクエリパラメータを取得後、Propsとして渡す。
export const getServerSideProps: GetServerSideProps = async (context) => {
  // リファラーから入力情報の訂正かどうか判定
  const referer = context.req.headers.referer || '';

  const isModifyInfo = referer.indexOf(CART_DELIVERY_CONFIRM) > -1;

  console.log('referer:' + referer);
  console.log('isModifyInfo:' + isModifyInfo);

  // propsとしてページコンポーネントに渡すデータを返す
  return {
    props: {
      isModifyInfo: isModifyInfo,
    },
  };
};

export default Main;
