import type { NextPage } from 'next';
import Head from 'next/head';

import SweepTopPageTemplate from '../../src/templates/sweeptemplatetop';

// http://localhost:3000/sweep/top
const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        ></meta>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SweepTopPageTemplate />
    </>
  );
};

export default Main;

/*  
SWEEP
画面構造
リンク一覧
Top
LineUp
Cart
DEliverInfo
DeliverConfirm
DeliverComplete

ファイル階層
「Page」
Top
LineUp
Cart
DEliverInfo
DeliverConfirm
DeliverComplete

『テンプレート』
toppage
lineppage
cartpage
deliverinfopage
deliverconfirmpage
delivercompletepage


『コンポーネント』(大体同じそうなもの)
header
itembox
divAnimate
spanAnimate

同じ画面内で使用しないものは
画面ごとの階層を切って使用する


基本構造
ヘッダーのカート数：Redux＋LocalStrage（使用するなら）
商品一覧、Topや最近見た商品一覧：Redux＆非同期
アニメーションを考えているパーツはクラス変更が前提のコンポを使用
商品詳細：クエリパラメータ＆非同期通信
お知らせ：非同期通信でデータ取得



*/
