import type { NextPage, GetServerSideProps } from 'next';

import Head from 'next/head';

import SweepNewsDetailTemplate from '../../../src/templates/sweepnewsdetailtemplate';

// GetServerSidePropsのPropsのインターフェース
export interface NewsDetailProps {
  newsId: string; //商品ID
}

const Main: NextPage<NewsDetailProps> = (props) => {
  // PropsからニュースIDを取得
  const id = props.newsId;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SweepNewsDetailTemplate newsId={id} />
    </>
  );
};

// サーバーサイドの処理を実施してクエリパラメータを取得後、Propsとして渡す。
export const getServerSideProps: GetServerSideProps = async (context) => {
  // クエリパラメータから商品IDを取得
  const id = context.query?.id !== undefined ? context.query.id : '0';

  // propsとしてページコンポーネントに渡すデータを返す
  return {
    props: {
      newsId: id,
    },
  };
};

export default Main;
